schema: schema.graphql
documents: '**/*.graphql'
extensions:
  endpoints:
    mainnet:
      url: https://mainnet.ackinacki.org/graphql
    shellnet:
      url: https://shellnet.ackinacki.org/graphql
