name: release acki.live

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "release acki.live"
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
      attestations: write

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: install dependencies
        run: npm install

      - name: build acki.live
        run: npm run build
        env:
          NODE_ENV: "production"
          ACKI_LIVE_FEATURES: '["stat","showcase","wasm"]'

      - name: attest build provenance
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: 'build/**'

      - name: setup ssh agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ACKI_LIVE_DEPLOY_KEY }}

      - name: release acki.live
        # language=bash
        run: |
          git config --global user.name "github-actions-bot"
          git config --global user.email "support+actions@github.com"
          npm run release
