name: release acki.live

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: "release acki.live"
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: install dependencies
        run: npm ci

      - name: build acki.live
        run: npm run build:production

      - name: setup ssh agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.ACKI_LIVE_DEPLOY_KEY }}

      - name: configure git user
        run: |
          git config --global user.name "github-actions-bot"
          git config --global user.email "support+actions@github.com"

      - name: release acki.live
        run: npm run release:gh-pages
