name: release shellnet.acki.live

on:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: "release shellnet.acki.live"
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: install dependencies
        run: npm install

      - name: build shellnet.acki.live
        # language=bash
        run: |
          npm run build
          rm -fr build/.github
          printf "User-agent: *\nDisallow: /\n" > build/robots.txt
        env:
          NODE_ENV: "production"
          ACKI_LIVE_GRAPHQL: "https://shellnet.ackinacki.org/graphql"

      - name: setup ssh agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SHELLNET_ACKI_LIVE_DEPLOY_KEY }}

      - name: release shellnet.acki.live
        # language=bash
        run: |
          ssh-keyscan -t ed25519 gitlab.com >> ~/.ssh/known_hosts
          git clone --depth=1 git@gitlab.com:ever-guild/shellnet.acki.live.git release
          rm -fr release/public/*
          cp -r build/* release/public/

          git config --global user.name "github-actions-bot"
          git config --global user.email "support+actions@github.com"
          git -C release add public
          git -C release commit -m "release"
          git -C release push origin main
